package com.hetero.model;

import java.time.LocalDate;

/**
 * Core domain entity representing a single task in the Hetero Task Management System.
 *
 * <p>Each {@code Task} instance maps directly to one row in the {@code tasks} SQLite
 * table.  The {@code id} field is auto-generated by the database and populated after
 * the first successful {@code INSERT} via {@link com.hetero.db.DatabaseManager#insert}.
 *
 * <p><b>Specification compliance — this class demonstrates:</b>
 * <ul>
 *   <li><b>Primitive data:</b>
 *       {@code id} is a primitive {@code int};
 *       {@code isCompleted} is a primitive {@code boolean}.</li>
 *   <li><b>Instance variables and objects:</b>
 *       All seven fields are private instance variables.
 *       {@code title}, {@code notes}, and {@code category} are {@link String} objects;
 *       {@code priority} is a custom {@link Priority} enum object;
 *       {@code dueDate} is a {@link LocalDate} object from the Java standard library.</li>
 *   <li><b>Imported classes:</b> {@link LocalDate} imported from {@code java.time}.</li>
 *   <li><b>Custom-built classes:</b> Uses the custom {@link Priority} enum defined
 *       in the same {@code model} package.</li>
 *   <li><b>Proper access control:</b> All fields are {@code private}; external access
 *       is exclusively through public getters and setters, protecting invariants
 *       (e.g. category is coerced to "General" if blank).</li>
 *   <li><b>Domain modelling:</b> Faithfully represents the Task concept with all
 *       attributes required by the project specification.</li>
 *   <li><b>Meaningful identifiers:</b> Every field and parameter uses a full,
 *       descriptive name — no abbreviations such as {@code t}, {@code dt}, etc.</li>
 * </ul>
 */
public class Task {

    // ── Private instance variables ────────────────────────────────────────────

    /**
     * Database-assigned primary key for this task.
     * Value is {@code 0} until the task has been persisted to SQLite.
     * Primitive {@code int} — demonstrates use of primitive data.
     */
    private int id;

    /**
     * Short descriptive title that identifies the task to the user.
     * Must never be {@code null} or blank — enforced at the controller layer.
     */
    private String title;

    /**
     * Optional free-form notes, description, or context for the task.
     * May be {@code null} when the user provides no additional detail.
     */
    private String notes;

    /**
     * Urgency level of this task.
     * Represented by the custom {@link Priority} enum defined in this package.
     */
    private Priority priority;

    /**
     * Organisational label grouping related tasks together
     * (e.g. "Work", "Personal", "Errands").
     * Defaults to {@code "General"} when no category is specified.
     */
    private String category;

    /**
     * Optional deadline for the task.
     * {@code null} when no due date has been assigned by the user.
     * Uses {@link LocalDate} (imported from {@code java.time}) to avoid
     * raw string date handling and time-zone ambiguity.
     */
    private LocalDate dueDate;

    /**
     * Completion flag for this task.
     * {@code true} when the user has marked the task as done;
     * {@code false} (the default) when the task is still pending.
     * Primitive {@code boolean} — demonstrates use of primitive data.
     */
    private boolean isCompleted;

    // ── Constructors ──────────────────────────────────────────────────────────

    /**
     * Full constructor used when hydrating a {@link Task} from the SQLite database,
     * where all fields — including the auto-generated {@code id} — are already known.
     *
     * @param id            the database-assigned primary key
     * @param title         the task title; must not be {@code null}
     * @param notes         optional notes text; may be {@code null}
     * @param priority      urgency level; must not be {@code null}
     * @param category      category label; coerced to {@code "General"} if blank or null
     * @param dueDate       optional deadline date; may be {@code null}
     * @param isCompleted   {@code true} if the task has already been completed
     */
    public Task(int id,
                String title,
                String notes,
                Priority priority,
                String category,
                LocalDate dueDate,
                boolean isCompleted) {

        this.id          = id;
        this.title       = title;
        this.notes       = notes;
        this.priority    = priority;
        this.category    = (category != null && !category.isBlank()) ? category : "General";
        this.dueDate     = dueDate;
        this.isCompleted = isCompleted;
    }

    /**
     * Creation constructor used when building a brand-new task that has not yet
     * been persisted to the database.
     *
     * <p>Delegates to the full constructor with {@code id = 0} and
     * {@code isCompleted = false} as safe defaults.
     *
     * @param title    the task title; must not be {@code null}
     * @param notes    optional notes text; may be {@code null}
     * @param priority urgency level; must not be {@code null}
     * @param category category label
     * @param dueDate  optional deadline date; may be {@code null}
     */
    public Task(String title,
                String notes,
                Priority priority,
                String category,
                LocalDate dueDate) {

        this(0, title, notes, priority, category, dueDate, false);
    }

    // ── Getters ───────────────────────────────────────────────────────────────

    /**
     * Returns the database-assigned primary key for this task.
     *
     * @return the task id; {@code 0} if the task has not yet been persisted
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the task title.
     *
     * @return the title string; never {@code null} for a valid task
     */
    public String getTitle() {
        return title;
    }

    /**
     * Returns the optional notes attached to this task.
     *
     * @return the notes string, or {@code null} if no notes have been provided
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Returns the urgency level of this task.
     *
     * @return the {@link Priority} enum value; never {@code null}
     */
    public Priority getPriority() {
        return priority;
    }

    /**
     * Returns the category label assigned to this task.
     *
     * @return the category string; never {@code null} — defaults to {@code "General"}
     */
    public String getCategory() {
        return category;
    }

    /**
     * Returns the optional due date for this task.
     *
     * @return a {@link LocalDate}, or {@code null} if no due date has been set
     */
    public LocalDate getDueDate() {
        return dueDate;
    }

    /**
     * Returns whether this task has been marked as completed.
     *
     * @return {@code true} if the task is done; {@code false} if still pending
     */
    public boolean isCompleted() {
        return isCompleted;
    }

    // ── Setters ───────────────────────────────────────────────────────────────

    /**
     * Sets the primary key after a successful database insert.
     * Should only be called by the repository layer.
     *
     * @param id the auto-generated id returned by SQLite
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Updates the task title.
     *
     * @param title the new title; must not be {@code null} or blank
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Updates the optional notes field.
     *
     * @param notes new notes content; may be {@code null} to clear notes
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * Updates the priority level.
     *
     * @param priority the new {@link Priority}; must not be {@code null}
     */
    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    /**
     * Updates the category label.
     * Null or blank values are coerced to {@code "General"} to maintain the invariant.
     *
     * @param category the new category string; {@code null} is coerced to "General"
     */
    public void setCategory(String category) {
        this.category = (category != null && !category.isBlank()) ? category : "General";
    }

    /**
     * Sets or clears the due date for this task.
     *
     * @param dueDate the new due date, or {@code null} to remove the deadline
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * Marks or unmarks this task as completed.
     *
     * @param completed {@code true} to mark the task done; {@code false} to reopen it
     */
    public void setCompleted(boolean completed) {
        this.isCompleted = completed;
    }

    // ── Object overrides ──────────────────────────────────────────────────────

    /**
     * Returns a compact, human-readable summary of this task.
     * Useful for console debugging and benchmark log output.
     *
     * @return formatted string representation of this task
     */
    @Override
    public String toString() {
        return "Task{id=%d, title='%s', priority=%s, category='%s', dueDate=%s, isCompleted=%b}"
                .formatted(id, title, priority, category, dueDate, isCompleted);
    }
}
